version: 0.2
phases:
  install:
    on-failure: ABORT 
    runtime-versions:
      php: 8.2
  
  pre_build:
    on-failure: ABORT 
    commands:
      - echo 'login in to Amazon ECR ...'
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT 
    commands:
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/new-elactic-base:latest
    
  post_build:
    on-failure: ABORT 
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/new-elactic-base:latest

